# -*- coding: utf-8 -*-
"""hw5_p6_lr2965.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jOh7z_g8BjSnjO-iN9OLre5Il4h_1gdQ
"""

import numpy as np
from sklearn import linear_model
from sklearn.metrics import accuracy_score

data = np.loadtxt(open("hw5p6data.csv", "rb"), delimiter=",", skiprows=1)

##Ref: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html

label = data[:,0]
x = data[:, 1:]


labelGPA = label[0:500]
labelSAT = label[500:599]

GPA = data[:500,0]
SAT = data[500:599, 1]

print(x.shape)


clf = linear_model.SGDClassifier(max_iter=1000, tol=1e-3, loss='log')
clf.fit(x, label)
pred = clf.predict(x)
err = 1 - accuracy_score(label, pred)

clfGPA = linear_model.SGDClassifier(max_iter=1000, tol=1e-3, loss='log')
clfSAT = linear_model.SGDClassifier(max_iter=1000, tol=1e-3, loss='log')

clfGPA.fit(GPA, label)
predGPA = clfGPA.predict(GPA)

clfSAT.fit(SAT, label)
predSAT = clfSAT.predict(SAT)

errGPA = 1 - accuracy_score(label, predGPA)
errSAT = 1 - accuracy_score(label, predSAT)

print('errGPA', errGPA)
print('errSAT', errSAT)